# Generated by Django 5.2.6 on 2025-11-24 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(db_column='cliente_dni', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='clientes.cliente')),
                ('vehiculo', models.ForeignKey(db_column='vehiculo_patente', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='vehiculos.vehiculo')),
            ],
            options={
                'db_table': 'RESERVAS',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
