# Generated by Django 4.2.25 on 2025-11-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "dni",
                    models.IntegerField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("telefono", models.IntegerField(max_length=15)),
            ],
        ),
    ]
