# Generated by Django 5.2.6 on 2025-11-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_dni_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='CLIENTES',
        ),
    ]
