# Generated by Django 5.2.6 on 2025-11-24 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(db_column='DNI_empleado', on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('vehiculo', models.ForeignKey(db_column='patente_vehiculo', on_delete=django.db.models.deletion.PROTECT, to='vehiculos.vehiculo')),
            ],
            options={
                'db_table': 'MANTENIMIENTOS',
            },
        ),
    ]
