# Generated by Django 5.2.6 on 2025-11-24 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empleados', '0001_initial'),
        ('reservas', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('total_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(db_column='cliente_dni', on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='clientes.cliente')),
                ('empleado', models.ForeignKey(db_column='empleado_dni', on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='empleados.empleado')),
                ('reserva', models.ForeignKey(blank=True, db_column='reserva_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquiler', to='reservas.reserva')),
                ('vehiculo', models.ForeignKey(db_column='vehiculo_patente', on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='vehiculos.vehiculo')),
            ],
            options={
                'db_table': 'ALQUILERES',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
