# Generated by Django 5.2.6 on 2025-11-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehiculo',
            table='VEHICULOS',
        ),
    ]
