# Generated by Django 5.2.8 on 2025-11-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
