# Generated by Django 5.2.8 on 2025-11-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danio',
            fields=[
                ('id_danio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alquiler', models.ForeignKey(db_column='ID_alquiler', on_delete=django.db.models.deletion.PROTECT, to='alquileres.alquiler')),
            ],
            options={
                'db_table': 'DANIOS',
            },
        ),
    ]
